---
spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    openInView: false
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.use_second_level_cache: false
      hibernate.hbm2ddl.auto: validate
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/pingpong
    username: root
    password:
    databaseName: ordersdb
    dataSourceClassName: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true
  messages:
    basename: locale/messages
    cache-seconds: -1
    encoding: UTF-8